spring:
  application:
    name: spring-boot-graphQL
  datasource:
    url: jdbc:mysql://localhost:3306/blogs_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 9091
  servlet:
    context-path: /blogs
